import StyleDictionary from 'style-dictionary'

// ─── Utilities ────────────────────────────────────────────────────────────────

function hexToHsl(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255
  const g = parseInt(hex.slice(3, 5), 16) / 255
  const b = parseInt(hex.slice(5, 7), 16) / 255
  const max = Math.max(r, g, b)
  const min = Math.min(r, g, b)
  let h = 0
  let s = 0
  const l = (max + min) / 2
  if (max !== min) {
    const d = max - min
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break
      case g: h = ((b - r) / d + 2) / 6; break
      case b: h = ((r - g) / d + 4) / 6; break
    }
  }
  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`
}

function makeLookup(dictionary) {
  return (group, shade) => {
    const token = dictionary.allTokens.find(
      (t) => t.path[0] === 'color' && t.path[1] === group && t.path[2] === shade
    )
    return token?.value ?? '#000000'
  }
}

// ─── Custom formats ───────────────────────────────────────────────────────────

StyleDictionary.registerFormat({
  name: 'custom/css-with-shadcn',
  format: ({ dictionary }) => {
    const tok = makeLookup(dictionary)

    // Group tokens by palette
    const palettes = {}
    dictionary.allTokens
      .filter((t) => t.path[0] === 'color')
      .forEach((t) => {
        const [, group, shade] = t.path
        if (!palettes[group]) palettes[group] = {}
        palettes[group][shade] = t.value
      })

    const labels = {
      grey: 'Grey',
      slate: 'Slate',
      blue: 'Blue',
      red: 'Red',
      yellow: 'Yellow',
      green: 'Green',
      violet: 'Violet — primary brand',
    }

    let css = '/** Auto-generated — run npm run sync to update */\n\n:root {\n'
    for (const [group, shades] of Object.entries(palettes)) {
      css += `  /* ── ${(labels[group] ?? group).padEnd(28)} */\n`
      for (const [shade, value] of Object.entries(shades)) {
        css += `  --tg-color-${group}-${shade}: ${value};\n`
      }
      css += '\n'
    }
    css = css.trimEnd() + '\n}\n'

    // Shadcn compat — raw HSL channel values (auto-computed from brand tokens above)
    // Shadcn's tailwind.config wraps these in hsl(), so values must be "H S% L%" not hex.
    const primary     = tok('violet', '500')  // #494fe8 — brand primary
    const fg          = tok('slate',  '900')  // #121417 — default text
    const secondaryBg = tok('slate',  '100')  // #dee0e3 — secondary surface
    const mutedFg     = tok('slate',  '500')  // #586574 — muted text
    const accentBg    = tok('violet', '100')  // #dbdcfa — accent surface
    const accentFg    = tok('violet', '700')  // #2c2f8b — accent text
    const destructive = tok('red',    '500')  // #a11b1b — error/danger
    const border      = tok('slate',  '200')  // #bcc1c7 — default borders

    css += `
/*
 * Shadcn/ui compatibility — raw HSL channel values, auto-computed from brand tokens.
 * Shadcn's Tailwind config wraps these in hsl(), e.g. hsl(var(--primary)).
 * Do not edit manually — regenerated by npm run sync.
 */
:root {
  --background:             0 0% 100%;
  --foreground:             ${hexToHsl(fg)};
  --card:                   0 0% 100%;
  --card-foreground:        ${hexToHsl(fg)};
  --popover:                0 0% 100%;
  --popover-foreground:     ${hexToHsl(fg)};
  --primary:                ${hexToHsl(primary)};
  --primary-foreground:     0 0% 100%;
  --secondary:              ${hexToHsl(secondaryBg)};
  --secondary-foreground:   ${hexToHsl(fg)};
  --muted:                  ${hexToHsl(secondaryBg)};
  --muted-foreground:       ${hexToHsl(mutedFg)};
  --accent:                 ${hexToHsl(accentBg)};
  --accent-foreground:      ${hexToHsl(accentFg)};
  --destructive:            ${hexToHsl(destructive)};
  --destructive-foreground: 0 0% 100%;
  --border:                 ${hexToHsl(border)};
  --input:                  ${hexToHsl(border)};
  --ring:                   ${hexToHsl(primary)};
  --radius:                 0.5rem;
}
`
    return css
  },
})

StyleDictionary.registerFormat({
  name: 'custom/tailwind-preset',
  format: ({ dictionary }) => {
    const palette = {}
    dictionary.allTokens
      .filter((t) => t.path[0] === 'color')
      .forEach((t) => {
        const [, group, shade] = t.path
        if (!palette[group]) palette[group] = {}
        palette[group][shade] = `var(--tg-color-${group}-${shade})`
      })

    const preset = {
      theme: {
        extend: {
          colors: {
            ...palette,
            // Shadcn semantic colors — use for theme-aware UI (bg-primary, text-foreground, etc.)
            background: 'hsl(var(--background))',
            foreground: 'hsl(var(--foreground))',
            card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
            popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
            primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
            secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
            muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
            accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
            destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
            border: 'hsl(var(--border))',
            input: 'hsl(var(--input))',
            ring: 'hsl(var(--ring))',
          },
          borderRadius: {
            DEFAULT: 'var(--radius)',
            sm: 'calc(var(--radius) - 2px)',
            md: 'var(--radius)',
            lg: 'calc(var(--radius) + 2px)',
            xl: 'calc(var(--radius) + 8px)',
            '2xl': 'calc(var(--radius) + 16px)',
          },
        },
      },
    }

    return `/** Auto-generated — run npm run sync to update */\nexport default ${JSON.stringify(preset, null, 2)}\n`
  },
})

StyleDictionary.registerFormat({
  name: 'custom/js-tokens',
  format: ({ dictionary }) => {
    const colors = {}
    dictionary.allTokens
      .filter((t) => t.path[0] === 'color')
      .forEach((t) => {
        const [, group, shade] = t.path
        if (!colors[group]) colors[group] = {}
        colors[group][shade] = t.value
      })

    const tok = makeLookup(dictionary)
    const semantic = {
      primary:       tok('violet', '500'),
      primaryHover:  tok('violet', '600'),
      secondary:     tok('blue',   '500'),
      secondaryHover:tok('blue',   '600'),
      success:       tok('green',  '500'),
      error:         tok('red',    '500'),
      warning:       tok('yellow', '500'),
      textDefault:   tok('slate',  '900'),
      textMuted:     tok('slate',  '500'),
      borderDefault: tok('slate',  '200'),
    }

    return (
      `/** Auto-generated — run npm run sync to update */\n` +
      `export const colors = ${JSON.stringify(colors, null, 2)}\n\n` +
      `export const semantic = ${JSON.stringify(semantic, null, 2)}\n`
    )
  },
})

// ─── Config ───────────────────────────────────────────────────────────────────

export default {
  source: ['tokens/figma-tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/generated/',
      files: [
        {
          destination: 'variables.css',
          format: 'custom/css-with-shadcn',
        },
      ],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'tokens/generated/',
      files: [
        {
          destination: 'tailwind-preset.js',
          format: 'custom/tailwind-preset',
        },
      ],
    },
    js: {
      transformGroup: 'js',
      buildPath: 'tokens/generated/',
      files: [
        {
          destination: 'tokens.js',
          format: 'custom/js-tokens',
        },
      ],
    },
  },
}
